### ISSUE TITLE
the plugin is not working with the newest fluent

### ISSUE THREAD

**Issue by geosone** [yudai09/fluent-plugin-postfix#1]
plz update the plugin to a working state

**Comment by yudai09** [comment]
I fix it.
The plugin must work.
(I pushed wrong repository. sorry.)

**Comment by geosone** [comment]
but still not working

https://gist.github.com/4461a7ad764ec05467ca.git

**Comment by yudai09** [comment]
Sorry. I can not access the link above. (Wrong URL?)

**Comment by geosone** [comment]
you are right i gave you the wrong link
https://gist.github.com/geosone/4461a7ad764ec05467ca

**Comment by yudai09** [comment]
Thank you for giving me the right URL.
It seems to be not wrong configration.
Then, I want to know the detail about how the plugin doesn't work with your environment.
The plugin doesn't emmit any log?
Or td-agent say something wrong with it?

**Comment by geosone** [comment]
no log line is written at all as you can see in the log it should foster an copy for the mail log tag 
i also tryed to do a simple source with postfix and a simple out file but nothing gets written.
i compared the logformat in postfix with your regexp and it schould match i also tryed reactivationg the log.warn entry also no entries lik it would not load the plugin correctly.
also deleted the pos files (the mail logs are a copy from the the productive system)

http://pastebin.com/yy0DFPHc
(will be gone in 1Hour)

here a small snip from the mail log

**Comment by yudai09** [comment]
regexp was wrong.
now it has been fixed.

**Comment by geosone** [comment]
still not working 
i will look into it tomorrow

**Comment by geosone** [comment]
not working i think it has something to do with forest 
i can give you access to the install this weekend if you want to test because i am running out of ideas.

**Comment by yudai09** [comment]
plugin work without forest? and the plugin doesn't work with forest?

**Comment by geosone** [comment]
no its not working with or without so still no luck

**Comment by yudai09** [comment]
This plugin works with the log which you gave me few days ago.
If you can give me, I want another logs.
If you don"t want to expose your log to the internet, mail me.

**Comment by geosone** [comment]
if you would like i can give you acces to a testinstall with enought logs

**Comment by yudai09** [comment]
OK. give me it.

**Comment by geosone** [comment]
ok will setup the server this evening and copy the logs to it and install the fluent system

**Comment by geosone** [comment]
2 years late but i am setting up the test system and fill it with ~4GB mail logs (how to excahnge the login infos)

**Comment by geosone** [comment]
all the issues have been fixed
